// Centralized game configuration
import type { GameConfigShape } from '../types/config.js';

const GameConfig: GameConfigShape = {
  world: {
    width: 4800,
    height: 4800,
    tileSize: 50,
  },

  entityCollision: {
    buffer: 12,
  },

  groundTextures: {
    grass: 'assets/sprites/environment/Grass1.png',
  },

  player: {
    startX: 2400,
    startY: 1400,
    width: 34.5,
    height: 34.5,
    speed: 280,
    maxHealth: 100,
    maxStamina: 100,
    staminaRegen: 16,
    color: '#8b8b9a',
    defaultWeapon: 'sword_rusty',
    defaultOffhand: 'none',
    sprint: { multiplier: 1.35, staminaCost: 12 },
    dodge: { speed: 800, duration: 0.15, cooldown: 0.5, staminaCost: 15 },
    knockback: {
      force: 1100,
      decay: 0.85,
      receivedMultiplier: 3.0,
      knockbackResist: 0,
    },
    projectile: {
      enabled: false,
      speed: 800,
      damage: 10,
      range: 500,
      cooldown: 0.125,
      staminaCost: 8,
      stunBuildup: 20,
    },
    crossbow: {
      damage: 22,
      speed: 1100,
      range: 600,
      staminaCost: 12,
      stunBuildup: 25,
      reloadTime: 0.35,
      perfectWindowStart: 0.62,
      perfectWindowEnd: 0.78,
      perfectReloadDamageMultiplier: 1.5,
    },
    bow: {
      damage: 14,
      speed: 950,
      range: 550,
      staminaCost: 8,
      stunBuildup: 20,
      /** Seconds to reach charge level 1 (min hold to fire one arrow). */
      chargeLevel1: 0.2,
      /** Seconds to reach charge level 2 (two arrows). */
      chargeLevel2: 0.5,
      /** Seconds to reach charge level 3 (three arrows). */
      chargeLevel3: 0.9,
    },
    heal: {
      maxCharges: 3,
      drinkTime: 1,
      regenRate: 50,
      regenDuration: 1,
      chargeRegenTime: 15,
    },
    stun: {
      threshold: 100,
      duration: 0.5,
      decayPerSecond: 30,
      decayCooldown: 2,
      blockedMultiplier: 0.5,
    },
  },

  statusEffects: {
    enemyStunThreshold: 100,
    enemyStunDuration: 0.5,
    enemyStunDecayPerSecond: 40,
    enemyStunDecayCooldown: 2,
  },

  enemy: {
    types: {} as Record<string, unknown>,
    pack: { radius: 180, minAllies: 2, modifierChance: 0.5 },
    /** Max enemies alive at once. Packs spawn when player is close (proximity), so high cap stays performant. */
    spawn: { maxEnemies: 80 },
  },

  packModifiers: {
    fierce: { damageMultiplier: 1.4, healthMultiplier: 1.25, color: '#cc2222' },
    swift: { speedMultiplier: 1.3, damageMultiplier: 1.05, color: '#ffcc00' },
    stalwart: { healthMultiplier: 1.6, knockbackResist: 0.5, damageMultiplier: 1.0, color: '#228822' },
    relentless: { attackCooldownMultiplier: 0.65, damageMultiplier: 1.15, color: '#6666ff' },
    vicious: { stunBuildupPerHitMultiplier: 1.5, damageMultiplier: 1.15, color: '#cc44cc' },
    inspiring: { speedMultiplier: 1.15, damageMultiplier: 1.2, healthMultiplier: 1.3, color: '#00aacc' },
  },

  portal: { x: 2360, y: 2360, width: 80, height: 80, channelTime: 1.2 },

  hub: {
    name: 'Sanctuary',
    tileSize: 50,
    width: 1600,
    height: 1600,
    playerStart: { x: 800, y: 950 },
    board: { x: 720, y: 780, width: 100, height: 70 },
    weaponChest: { x: 320, y: 900, width: 80, height: 60 },
    shopkeeper: { x: 1240, y: 900, width: 56, height: 56 },
    rerollStation: { x: 700, y: 340, width: 64, height: 64 },
    questPortal: { x: 760, y: 520, width: 80, height: 80 },
    trainingDummy: { x: 480, y: 920 },
    theme: {
      ground: { r: 42, g: 52, b: 38, variation: 8, texture: 'grass' },
      sky: 'rgba(180, 200, 220, 0.12)',
      clearColor: '#2a3238',
    },
    wallColor: '#6b5b4f',
    fence: { originX: 200, originY: 200, width: 1150, height: 1150, spacing: 36, size: 32, gapSide: 'bottom', gapWidth: 140, fenceColor: '#8b7355' },
    walls: [
      { x: 200, y: 200, width: 1200, height: 50 },
      { x: 200, y: 1350, width: 1200, height: 50 },
      { x: 200, y: 200, width: 50, height: 1200 },
      { x: 1350, y: 200, width: 50, height: 1200 },
    ],
    decorations: [
      { type: 'firepit', x: 735, y: 600, width: 50, height: 50 },
      { type: 'barrel', x: 300, y: 860 },
      { type: 'barrel', x: 1270, y: 860 },
      { type: 'brazier', x: 665, y: 340, width: 40, height: 40 },
      { type: 'brazier', x: 915, y: 340, width: 40, height: 40 },
      // Flavor: corners and edges
      { type: 'bush', x: 260, y: 260, width: 28, height: 28 },
      { type: 'bush', x: 1290, y: 260, width: 28, height: 28 },
      { type: 'bush', x: 260, y: 1290, width: 28, height: 28 },
      { type: 'bush', x: 1290, y: 1290, width: 28, height: 28 },
      { type: 'bush', x: 420, y: 280 },
      { type: 'bush', x: 1120, y: 300 },
      { type: 'pillar', x: 620, y: 760, width: 42, height: 42 },
      { type: 'pillar', x: 838, y: 760, width: 42, height: 42 },
      { type: 'column', x: 740, y: 460, width: 38, height: 38 },
      { type: 'column', x: 820, y: 460, width: 38, height: 38 },
      { type: 'statueBase', x: 580, y: 320, width: 52, height: 52 },
      { type: 'statueBase', x: 918, y: 320, width: 52, height: 52 },
      { type: 'well', x: 1080, y: 280, width: 48, height: 48 },
      { type: 'brazier', x: 340, y: 840, width: 38, height: 38 },
      { type: 'brazier', x: 1220, y: 840, width: 38, height: 38 },
      { type: 'barrel', x: 1180, y: 870 },
      { type: 'stoneDebris', x: 230, y: 400 },
      { type: 'stoneDebris', x: 1320, y: 1150 },
      { type: 'mushroom', x: 380, y: 880, width: 22, height: 22 },
      { type: 'mushroom', x: 1310, y: 250, width: 18, height: 18 },
      // More flavor
      { type: 'bush', x: 600, y: 1280 },
      { type: 'bush', x: 950, y: 1260 },
      { type: 'pillar', x: 280, y: 380, width: 38, height: 38 },
      { type: 'pillar', x: 1260, y: 380, width: 38, height: 38 },
      { type: 'column', x: 250, y: 600, width: 36, height: 36 },
      { type: 'column', x: 1300, y: 600, width: 36, height: 36 },
      { type: 'rubble', x: 550, y: 1280, width: 32, height: 32 },
      { type: 'rubble', x: 1000, y: 1270, width: 28, height: 28 },
      { type: 'stoneDebris', x: 650, y: 420 },
      { type: 'stoneDebris', x: 920, y: 1280 },
      { type: 'barrel', x: 270, y: 830 },
      { type: 'brazier', x: 800, y: 680, width: 36, height: 36 },
      { type: 'mushroom', x: 720, y: 1285, width: 16, height: 16 },
      { type: 'mushroom', x: 860, y: 1270, width: 20, height: 20 },
    ],
  },

  levels: {
    0: {
      name: 'Sanctuary',
      tileSize: 50,
      width: 1600,
      height: 1600,
      playerStart: { x: 800, y: 950 },
      board: { x: 720, y: 780, width: 100, height: 70 },
      weaponChest: { x: 320, y: 900, width: 80, height: 60 },
      shopkeeper: { x: 1240, y: 900, width: 56, height: 56 },
      rerollStation: { x: 700, y: 340, width: 64, height: 64 },
      trainingDummy: { x: 480, y: 920 },
      theme: {
        ground: { r: 42, g: 52, b: 38, variation: 8, texture: 'grass' },
        sky: 'rgba(180, 200, 220, 0.12)',
        clearColor: '#2a3238',
      },
      wallColor: '#6b5b4f',
      fence: { originX: 200, originY: 200, width: 1150, height: 1150, spacing: 36, size: 32, gapSide: 'bottom', gapWidth: 140, fenceColor: '#8b7355' },
      walls: [
        { x: 200, y: 200, width: 1200, height: 50 },
        { x: 200, y: 1350, width: 1200, height: 50 },
        { x: 200, y: 200, width: 50, height: 1200 },
        { x: 1350, y: 200, width: 50, height: 1200 },
      ],
      decorations: [
        { type: 'firepit', x: 735, y: 600, width: 50, height: 50 },
        { type: 'barrel', x: 300, y: 860 },
        { type: 'barrel', x: 1270, y: 860 },
        { type: 'brazier', x: 665, y: 340, width: 40, height: 40 },
        { type: 'brazier', x: 915, y: 340, width: 40, height: 40 },
        { type: 'bush', x: 260, y: 260, width: 28, height: 28 },
        { type: 'bush', x: 1290, y: 260, width: 28, height: 28 },
        { type: 'bush', x: 260, y: 1290, width: 28, height: 28 },
        { type: 'bush', x: 1290, y: 1290, width: 28, height: 28 },
        { type: 'bush', x: 420, y: 280 },
        { type: 'bush', x: 1120, y: 300 },
        { type: 'pillar', x: 620, y: 760, width: 42, height: 42 },
        { type: 'pillar', x: 838, y: 760, width: 42, height: 42 },
        { type: 'column', x: 740, y: 460, width: 38, height: 38 },
        { type: 'column', x: 820, y: 460, width: 38, height: 38 },
        { type: 'statueBase', x: 580, y: 320, width: 52, height: 52 },
        { type: 'statueBase', x: 918, y: 320, width: 52, height: 52 },
        { type: 'well', x: 1080, y: 280, width: 48, height: 48 },
        { type: 'brazier', x: 340, y: 840, width: 38, height: 38 },
        { type: 'brazier', x: 1220, y: 840, width: 38, height: 38 },
        { type: 'barrel', x: 1180, y: 870 },
        { type: 'stoneDebris', x: 230, y: 400 },
        { type: 'stoneDebris', x: 1320, y: 1150 },
        { type: 'mushroom', x: 380, y: 880, width: 22, height: 22 },
        { type: 'mushroom', x: 1310, y: 250, width: 18, height: 18 },
        { type: 'bush', x: 600, y: 1280 },
        { type: 'bush', x: 950, y: 1260 },
        { type: 'pillar', x: 280, y: 380, width: 38, height: 38 },
        { type: 'pillar', x: 1260, y: 380, width: 38, height: 38 },
        { type: 'column', x: 250, y: 600, width: 36, height: 36 },
        { type: 'column', x: 1300, y: 600, width: 36, height: 36 },
        { type: 'rubble', x: 550, y: 1280, width: 32, height: 32 },
        { type: 'rubble', x: 1000, y: 1270, width: 28, height: 28 },
        { type: 'stoneDebris', x: 650, y: 420 },
        { type: 'stoneDebris', x: 920, y: 1280 },
        { type: 'barrel', x: 270, y: 830 },
        { type: 'brazier', x: 800, y: 680, width: 36, height: 36 },
        { type: 'mushroom', x: 720, y: 1285, width: 16, height: 16 },
        { type: 'mushroom', x: 860, y: 1270, width: 20, height: 20 },
      ],
    },
    1: {
      name: 'Village Outskirts',
      packSpawn: {
        density: 0.008,
        packSize: { min: 2, max: 4 },
        patrol: false,
        packSpread: { min: 40, max: 95 },
        packCountVariance: 0.35,
        minPackDistance: 220,
      },
      enemyTypes: ['goblin', 'goblin', 'goblin', 'goblin', 'goblinChieftain', 'bandit'],
      killsToUnlockPortal: 30,
      theme: {
        ground: { r: 38, g: 48, b: 38, variation: 8, texture: 'grass' },
        sky: 'rgba(135, 206, 235, 0.05)',
      },
      worldWidth: 4800,
      worldHeight: 4800,
      obstacles: {
        border: { spacing: 50 },
        useSceneTiles: true,
        sceneTileLayout: {
          tileSize: 1200,
          cols: 4,
          rows: 4,
          pool: [
            { id: 'clearing', weight: 5 },
            { id: 'crossroads', weight: 4 },
            { id: 'orchardEdge', weight: 3 },
            { id: 'thickGrove', weight: 3 },
            { id: 'waysideShrine', weight: 2 },
            { id: 'woodcutterClearing', weight: 2 },
            { id: 'lumberMill', weight: 1 },
            { id: 'lumberMillB', weight: 1 },
            { id: 'smallFarm', weight: 1 },
            { id: 'goblinCamp', weight: 1 },
            { id: 'goblinCampB', weight: 1 },
            { id: 'banditAmbush', weight: 0.4 },
          ],
        },
      },
    },
    2: {
      name: 'Cursed Wilds',
      packSpawn: {
        density: 0.012,
        packSize: { min: 3, max: 5 },
        patrol: false,
        packSpread: { min: 45, max: 100 },
        packCountVariance: 0.35,
        minPackDistance: 240,
      },
      enemyTypes: ['goblin', 'goblin', 'goblinChieftain', 'skeleton', 'skeleton', 'zombie', 'zombie'],
      enemyTier2Chance: 0.4,
      killsToUnlockPortal: 40,
      theme: {
        ground: { r: 28, g: 26, b: 24, variation: 10 },
        sky: 'rgba(60, 55, 70, 0.08)',
      },
      worldWidth: 4800,
      worldHeight: 4800,
      obstacles: {
        border: { spacing: 50, type: 'deadTree' },
        useSceneTiles: true,
        sceneTileLayout: {
          tileSize: 1200,
          cols: 4,
          rows: 4,
          pool: [
            { id: 'cursedWilds.clearing', weight: 5 },
            { id: 'cursedWilds.crossroads', weight: 4 },
            { id: 'cursedWilds.bogClearing', weight: 3 },
            { id: 'cursedWilds.swampEdge', weight: 3 },
            { id: 'cursedWilds.ruinedShrine', weight: 2 },
            { id: 'cursedWilds.thickMushroomGrove', weight: 2 },
            { id: 'cursedWilds.ruinFragment', weight: 1 },
            { id: 'cursedWilds.graveyard', weight: 1 },
            { id: 'cursedWilds.graveyardB', weight: 1 },
            { id: 'cursedWilds.skeletonCamp', weight: 0.5 },
          ],
        },
      },
    },
    3: {
      name: 'Demon Approach',
      packSpawn: {
        density: 0.016,
        packSize: { min: 4, max: 6 },
        packSpread: { min: 50, max: 110 },
        packCountVariance: 0.4,
        minPackDistance: 260,
      },
      enemyTypes: ['skeleton', 'skeleton', 'lesserDemon', 'lesserDemon', 'greaterDemon', 'zombie', 'zombie'],
      enemyTier2Chance: 0.4,
      killsToUnlockPortal: 50,
      theme: {
        ground: {
          r: 42, g: 38, b: 32,
          variation: 6,
          patch: { r: 58, g: 22, b: 26, variation: 10, chance: 0.22 },
        },
        sky: 'rgba(80, 20, 30, 0.12)',
      },
      worldWidth: 4800,
      worldHeight: 4800,
      obstacles: {
        border: { spacing: 50, type: 'lavaRock' },
        useSceneTiles: true,
        sceneTileLayout: {
          tileSize: 1200,
          cols: 4,
          rows: 4,
          pool: [
            { id: 'demonApproach.clearing', weight: 5 },
            { id: 'demonApproach.crossroads', weight: 4 },
            { id: 'demonApproach.pillarRing', weight: 3 },
            { id: 'demonApproach.lavaRockField', weight: 3 },
            { id: 'demonApproach.demonShrine', weight: 2 },
            { id: 'demonApproach.brazierCourt', weight: 2 },
            { id: 'demonApproach.ashenPlaza', weight: 2 },
            { id: 'demonApproach.ruinedGate', weight: 1 },
            { id: 'demonApproach.ruinFragment', weight: 1 },
            { id: 'demonApproach.demonCamp', weight: 1 },
            { id: 'demonApproach.skeletonCamp', weight: 0.5 },
          ],
        },
      },
    },
    4: {
      name: 'The Fort',
      packSpawn: {
        density: 0.018,
        packSize: { min: 4, max: 6 },
        packSpread: { min: 50, max: 110 },
        packCountVariance: 0.4,
        minPackDistance: 260,
      },
      enemyTypes: ['skeleton', 'skeleton', 'bandit', 'lesserDemon', 'greaterDemon', 'goblinChieftain'],
      enemyTier2Chance: 0.35,
      enemyTier3Chance: 0.35,
      killsToUnlockPortal: 60,
      theme: {
        ground: {
          r: 52, g: 50, b: 48,
          variation: 6,
          patch: { r: 42, g: 44, b: 46, variation: 8, chance: 0.18 },
        },
        sky: 'rgba(70, 68, 75, 0.1)',
      },
      worldWidth: 4800,
      worldHeight: 4800,
      obstacles: {
        border: { spacing: 50, type: 'rock' },
        useSceneTiles: true,
        sceneTileLayout: {
          tileSize: 1200,
          cols: 4,
          rows: 4,
          pool: [
            { id: 'fort.clearing', weight: 5 },
            { id: 'fort.crossroads', weight: 4 },
            { id: 'fort.barracks', weight: 5 },
            { id: 'fort.armory', weight: 4 },
            { id: 'fort.gatehouse', weight: 1 },
            { id: 'fort.tower', weight: 1 },
          ],
        },
      },
    },
    5: {
      name: 'Elder Woods',
      packSpawn: {
        density: 0.009,
        packSize: { min: 2, max: 4 },
        patrol: false,
        packSpread: { min: 42, max: 98 },
        packCountVariance: 0.35,
        minPackDistance: 230,
      },
      enemyTypes: ['goblin', 'goblin', 'goblinChieftain', 'bandit', 'bandit'],
      enemyTier2Chance: 0.35,
      enemyTier3Chance: 0.4,
      killsToUnlockPortal: 70,
      theme: {
        ground: { r: 32, g: 42, b: 32, variation: 9, texture: 'grass' },
        sky: 'rgba(100, 130, 100, 0.06)',
      },
      worldWidth: 4800,
      worldHeight: 4800,
      obstacles: {
        border: { spacing: 50, type: 'tree' },
        useSceneTiles: true,
        sceneTileLayout: {
          tileSize: 1200,
          cols: 4,
          rows: 4,
          pool: [
            { id: 'elderWoods.clearing', weight: 5 },
            { id: 'elderWoods.crossroads', weight: 4 },
            { id: 'elderWoods.pathBetweenTrunks', weight: 4 },
            { id: 'elderWoods.giantTrunkGrove', weight: 3 },
            { id: 'elderWoods.orchardEdge', weight: 3 },
            { id: 'elderWoods.waysideShrine', weight: 2 },
            { id: 'elderWoods.woodcutterClearing', weight: 2 },
            { id: 'elderWoods.outskirtsCamp', weight: 1 },
            { id: 'elderWoods.banditAmbush', weight: 0.4 },
          ],
        },
      },
    },
    10: {
      name: 'Delve',
      packSpawn: {
        density: 0.012,
        packSize: { min: 2, max: 4 },
        patrol: false,
        packSpread: { min: 40, max: 90 },
        packCountVariance: 0.35,
        minPackDistance: 200,
      },
      enemyTypes: ['goblin', 'goblin', 'skeleton', 'skeleton', 'zombie', 'bandit'],
      theme: {
        ground: { r: 42, g: 34, b: 28, variation: 10 },
        sky: 'rgba(18, 14, 12, 0.14)',
      },
      worldWidth: 1200,
      worldHeight: 1200,
      obstacles: {
        border: { spacing: 40, type: 'rock' },
        useSceneTiles: true,
        sceneTileLayout: {
          tileSize: 1200,
          cols: 1,
          rows: 1,
          pool: [{ id: 'delve.dirt', weight: 1 }],
        },
      },
    },
    11: {
      name: 'Dragon Arena',
      worldWidth: 1200,
      worldHeight: 1200,
      bossSpawn: { x: 600, y: 220, type: 'fireDragon' },
      killsToUnlockPortal: 1,
      enemyTypes: ['fireDragon'],
      theme: {
        ground: { r: 38, g: 24, b: 22, variation: 8 },
        sky: 'rgba(60, 20, 18, 0.14)',
      },
      obstacles: {
        border: { spacing: 40, type: 'rock' },
        useSceneTiles: true,
        sceneTileLayout: {
          tileSize: 1200,
          cols: 1,
          rows: 1,
          pool: [{ id: 'dungeon.dragonArena', weight: 1 }],
        },
      },
    },
  },

  obstacles: {
    forest: { density: 0.025 },
    rocks: { density: 0.022 },
    border: { spacing: 50 },
    structures: {
      houses: { enabled: true, count: 3 },
      woodClusters: { enabled: true, count: 3, treesPerCluster: 6 },
      settlements: { enabled: true, count: 1 },
      firepits: { enabled: true, count: 2 },
      sheds: { enabled: true, count: 2 },
      wells: { enabled: true, count: 1 },
      ruins: {
        enabled: true,
        rubblePiles: 12,
        pillarClusters: 6,
        ruinedWalls: 8,
        ruinedStructures: 4,
        brokenArches: 5,
        statueRemnants: 6,
      },
    },
  },

  pathfinding: { cellSize: 25 },

  camera: {
    smoothing: 0.1,
    fastFollowSmoothing: 0.35,
    minZoom: 1.0,
    maxZoom: 2.0,
    zoomSpeed: 0.1,
  },
};

export { GameConfig };
